### ISSUE TITLE
Deepimpute "has no loss to optimize"

### ISSUE THREAD

**Issue by ShadowUnicorn90** [lanagarmire/deepimpute#24]
Hello!  I'm trying to run deepimpute using the following code:

```
from deepimpute.multinet import MultiNet
import pandas
import numpy

data = pandas.read_csv('train_rectified_tc_matrix.csv', index_col=0)

#Get a list of transcripts.
tscripts = []
for col in data.columns:
    if(col != 'File'):
        tscripts.append(col)

multinet = MultiNet()

multinet.fit(data, cell_subset=1, genes_to_impute=tscripts)

#Now get validation data and prepare for prediction.
valdata = pandas.read_csv('rectified_tc_matrix.csv', index_col=0)
tscripts = []
barcodes = []
for col in valdata.columns:
    if(col != 'File'):
        tscripts.append(col)
for item in valdata.index:
    item = item.split('/')[-1]
    item = item.split('-')[0]
    barcodes.append(item)

#Now load matrix into memory.
valmatrix = numpy.zeros((len(barcodes), len(tscripts)))

for i in range(len(tscripts)):
    valmatrix[:, i] = data[tscripts[i]]

#For each noise level, create a repeatably random
for noise_level in [0.0, 0.125, 0.25, 0.5, 1.0]:
    numpy.random.seed(1337)
    inputmatrix = numpy.zeros(valmatrix.shape)

    for i in range(len(barcodes)):
        for j in range(len(tscripts)):
            if(numpy.random.ranf() < noise_level):
                inputmatrix[i, j] = 0.0
            else:
                inputmatrix[i, j] = valmatrix[i, j]

    #Get the inputmatrix into a DataFrame.
    inputdata = pandas.DataFrame(data=inputmatrix, index=barcodes, cols=tscripts)

    #Predict and save prediction.
    multinet.predict(inputdata).to_csv('deepimpute-prediction_noise_' + str(noise_level) + '.csv')
```

When I run this, I get the following error:
```
2020-04-27 15:08:09.029980: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda-10.1/lib64
2020-04-27 15:08:09.030077: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda-10.1/lib64
2020-04-27 15:08:09.030087: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Using TensorFlow backend.
                                                    NM_001007596_2  ...  NM_010239_2
File                                                                ...         
/data/trl_data/autoencode_Data/h5graphs/GCGACCA...        2.425532  ...     3.751592
/data/trl_data/autoencode_Data/h5graphs/AACGTTG...        1.876209  ...     7.863057
/data/trl_data/autoencode_Data/h5graphs/CGTTCTG...        3.160542  ...     2.541401
/data/trl_data/autoencode_Data/h5graphs/CAGCTGG...        1.690522  ...     3.261146
/data/trl_data/autoencode_Data/h5graphs/CCTAGCT...        6.174081  ...     3.388535
...                                                            ...  ...          ...
/data/trl_data/autoencode_Data/h5graphs/GGGATGA...        0.731141  ...     2.168790
/data/trl_data/autoencode_Data/h5graphs/TACTTGT...        2.793037  ...     2.420382
/data/trl_data/autoencode_Data/h5graphs/CGACCTT...        1.396518  ...     0.968153
/data/trl_data/autoencode_Data/h5graphs/GACGTTA...       14.038685  ...     6.292994
/data/trl_data/autoencode_Data/h5graphs/CACCTTG...        4.042553  ...     0.726115

[100 rows x 100 columns]
['NM_001007596_2', 'NM_001024728_2', 'NM_001039392_2', 'NM_001160239_2', 'NM_001190258_1', 'NM_001190327_1', 'NM_001190436_1', 'NM_001271590_1', 'NM_001271591_1', 'NM_001310726_1', 'NM_001313984_1', 'NM_007393_5', 'NM_007475_5', 'NM_007990_3', 'NM_008503_5', 'NM_008972_2', 'NM_009081_2', 'NM_009084_4', 'NM_009091_2', 'NM_009092_3', 'NM_009093_2', 'NM_009234_6', 'NM_009429_3', 'NM_010106_2', 'NM_010240_2', 'NM_010807_4', 'NM_011291_5', 'NM_011292_2', 'NM_011296_2', 'NM_011297_2', 'NM_011508_2', 'NM_011653_2', 'NM_011655_5', 'NM_011664_4', 'NM_016738_5', 'NM_016844_2', 'NM_018853_3', 'NM_018860_4', 'NM_019647_6', 'NM_019682_4', 'NM_019883_3', 'NM_021278_2', 'NM_023133_1', 'NM_024175_3', 'NM_024218_4', 'NM_025284_4', 'NM_026069_3', 'NM_027015_4', 'NM_029751_4', 'NM_029767_2', 'NM_053071_2', 'NM_170669_2', 'NM_172086_2', 'NM_198657_2', 'NM_207523_2', 'NR_033727_1', 'NM_001002239_3', 'NM_001033865_1', 'NM_001048057_1', 'NM_001048058_1', 'NM_001130484_1', 'NM_001130485_1', 'NM_001146707_1', 'NM_001159375_1', 'NM_001159483_1', 'NM_001170540_1', 'NM_001199350_1', 'NM_001252218_1', 'NM_001252219_1', 'NM_001258458_1', 'NM_001301340_1', 'NM_001301341_1', 'NM_001301343_1', 'NM_001301344_1', 'NM_001301345_1', 'NM_001313894_1', 'NM_001313923_1', 'NM_001316995_1', 'NM_001317385_1', 'NM_001324533_1', 'NM_001324534_1', 'NM_007687_5', 'NM_008210_5', 'NM_008211_3', 'NM_008258_1', 'NM_008302_3', 'NM_008907_1', 'NM_009077_2', 'NM_009078_2', 'NM_009080_2', 'NM_009082_3', 'NM_009094_2', 'NM_009095_2', 'NM_009096_3', 'NM_009098_2', 'NM_009156_2', 'NM_009438_5', 'NM_009448_4', 'NM_009609_3', 'NM_010239_2']
Using all the cores (32)
Input dataset is 100 cells (rows) and 100 genes (columns)
First 3 rows and columns:
                                                    NM_001007596_2  ...  NM_001039392_2
File                                                                ...         
/data/trl_data/autoencode_Data/h5graphs/GCGACCA...        2.425532  ...       10.530351
/data/trl_data/autoencode_Data/h5graphs/AACGTTG...        1.876209  ...       15.559105
/data/trl_data/autoencode_Data/h5graphs/CGTTCTG...        3.160542  ...       16.012780

[3 rows x 3 columns]
The number of input genes is not a multiple of 100. Filling with other genes.
Normalization
Building network
[{'type': 'dense', 'neurons': 256, 'activation': 'relu'}, {'type': 'dropout', 'rate': 0.2}]
Traceback (most recent call last):
  File "train-val_deepimpute.py", line 17, in <module>
    multinet.fit(data, cell_subset=1, genes_to_impute=tscripts)
  File "/home/jstubblefield/.local/share/virtualenvs/autoencode_RNA_SEQ-p1OSA3Wf/lib/python3.6/site-packages/deepimpute/multinet.py", line 218, in fit
    model = self.build([len(genes) for genes in self.predictors])
  File "/home/jstubblefield/.local/share/virtualenvs/autoencode_RNA_SEQ-p1OSA3Wf/lib/python3.6/site-packages/deepimpute/multinet.py", line 165, in build
    loss=loss)
  File "/home/jstubblefield/.local/share/virtualenvs/autoencode_RNA_SEQ-p1OSA3Wf/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/home/jstubblefield/.local/share/virtualenvs/autoencode_RNA_SEQ-p1OSA3Wf/lib/python3.6/site-packages/keras/engine/training.py", line 229, in compile
    self.total_loss = self._prepare_total_loss(masks)
  File "/home/jstubblefield/.local/share/virtualenvs/autoencode_RNA_SEQ-p1OSA3Wf/lib/python3.6/site-packages/keras/engine/training.py", line 706, in _prepare_total_loss
    raise ValueError('The model cannot be compiled '
ValueError: The model cannot be compiled because it has no loss to optimize.
```
I have had no luck fixing this on my own, and I would appreciate any help that you could provide.

**Comment by Puumanamana** [comment]
Hi,
Thanks for reporting this issue. I was able to fix a bug, but I'm not sure it will solve your problem completely. Still, try with the latest version (with `pip install .` after downloading the github repository) and let me know how it works.
Unfortunately, I was not able to reproduce your exact error. Could you show me your version of TensorFlow and Keras? For instance, you can see that with:
```python
import tensorflow
import keras

print(tensorflow.__version__)
print(keras.__version__)
```

Finally, what could definitely help would be to have the dataset itself to try it myself directly, if the data is not too sensitive of course.

**Comment by ShadowUnicorn90** [comment]
I'm using tensorflow 2.1.0 and keras 2.3.1.  My data is not sensitive, so
I'll attach it.  Thank you so much for the help!

**Comment by Puumanamana** [comment]
Thanks. You can send me the data directly at carisdak@hawaii.edu

**Comment by Puumanamana** [comment]
Hi,
Thanks for the dataset. I found the issue and push my changes.

However, since you have only 100 genes to impute in your dataset, I would advise you to use a lower value for the sub-networks (e.g. 20) like this:
```
multinet = MultiNet(sub_outputdim=20)
multinet.fit(data, cell_subset=1, genes_to_impute=tscripts)
```

Let me know if you run into other issues.
Cédric

**Comment by ShadowUnicorn90** [comment]
Thank you so much!  It ran perfectly!
