### ISSUE TITLE
ValueError: attempt to get argmin of an empty sequence

### ISSUE THREAD

**Issue by Zhangxf-ccnu** [lanagarmire/deepimpute#4]
Dear Lana Garmire,

Trying to run deepimpute with the data likes this (log transformed data), 

  | Atp1b2 | Sub1 | Ptprf
-- | -- | -- | --
1772071015_C02 | 2.302585 | 3.367296 | 0
1772071017_G12 | 1.791759 | 3.73767 | 0
1772071017_A05 | 2.197225 | 4.060443 | 1.609438

I ran into the following issue:

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Gene prediction limit set to 29 genes
Traceback (most recent call last):
  File "C:\Users\zhang\AppData\Local\Programs\Python\Python35\Lib\site-packages\deepimpute\deepImpute.py", line 114, in <module>
    data, n_cores=args.cores, NN_lim=args.limit, cell_subset=args.subset, **NN_params
  File "C:\Users\zhang\AppData\Local\Programs\Python\Python35\Lib\site-packages\deepimpute\deepImpute.py", line 17, in deepImpute
    multi.fit(data, NN_lim=NN_lim, cell_subset=cell_subset)
  File "C:\ProgramData\Anaconda3\lib\site-packages\deepimpute-0.0.1-py3.6.egg\deepimpute\multinet.py", line 157, in fit
    predictorLimit=self.predictorLimit,
  File "C:\ProgramData\Anaconda3\lib\site-packages\deepimpute-0.0.1-py3.6.egg\deepimpute\util.py", line 85, in get_input_genes
    [get_maxes(distanceMatrix.loc[gene], dims[0]) for gene in genes]
  File "C:\ProgramData\Anaconda3\lib\site-packages\deepimpute-0.0.1-py3.6.egg\deepimpute\util.py", line 85, in <listcomp>
    [get_maxes(distanceMatrix.loc[gene], dims[0]) for gene in genes]
  File "C:\ProgramData\Anaconda3\lib\site-packages\deepimpute-0.0.1-py3.6.egg\deepimpute\util.py", line 52, in get_maxes
    currentMinIdxInTopValues = np.argmin(topValues)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 1068, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence

When trying to run deepimpute with the data likes this (raw count), deepimpute  can be run without error.

  | Atp1b2 | Sub1 | Ptprf
-- | -- | -- | --
1772071015_C02 | 9 | 28 | 0
1772071017_G12 | 5 | 41 | 0
1772071017_A05 | 8 | 57 | 4

So, can I run deepimpute  the log transformed data? Thanks!

Regards,

Xiao-Fei Zhang

**Comment by Puumanamana** [comment]
Dear Xiao-Fei Zhang,

Actually, DeepImpute takes care of the log-transformation, you don't need to do it yourself. If you log-transform the data, it will work with the log(log()) data. Still, it should not be a problem and I will investigate it further.

Best,
Cedric
